### PR TITLE
Split into noarch libs and arch64 wrappers

### PR DESCRIPTION
**Pull request by manics**
- Switch to GitHub workflows
- Install package to PKG_NAME-PKG_VERSION-PKG_BUILDNUM
- Similar to ome/conda-bioformats2raw#4

Since there's no bump to the version we can wait for the next release before tagging

### CODE REVIEW

**Comment by jburel** [comment]
Can you add GHA badge to the readme?
I have closed my PR

**Comment by manics** [comment]
Last commit adds a workflow badge to the README

**Comment by jburel** [comment]
Everything is in place.
We can push a tag when a new version of the ``raw2ometiff`` is released.
Merging.

**Comment by joshmoore** [comment]
Might be worth pushing a bump of the build number to test it out.

**Pull request merged**
